In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
df = pd.read_csv('/home/nayara/trabalhoPy/trabalhoPy_env/consulta_cand_2014_SP.csv',header=0,encoding='ISO-8859-1', delimiter=';')

In [3]:
df.iloc[0:,[17,28,38,42]]

                          NM_CANDIDATO SG_PARTIDO DT_NASCIMENTO  DS_GENERO
0                FLAUDIO AZEVEDO LIMAS         PT    09/10/1961  MASCULINO
1              AUREA RODRIGUES MADEIRO       PMDB    18/02/1964   FEMININO
2     ALMIRANDO FERREIRA DO NASCIMENTO        PSB    24/07/1974  MASCULINO
3          HILDEBRANDO NERY DE ALMEIDA        PRB    23/03/1978  MASCULINO
4        JOSÉ MARIA RODRIGUES DE MATOS        PMN    10/12/1962  MASCULINO
...                                ...        ...           ...        ...
3659                     ALCEU GIRALDI        PSB    04/08/1955  MASCULINO
3660             NIVALDO SANTANA SILVA    PC do B    23/09/1953  MASCULINO
3661          MÔNICA DE OLIVEIRA COSTA        PHS    28/03/1986   FEMININO
3662      WALTER JOSÉ GONÇALVES JUNIOR       PSDC    12/08/1982  MASCULINO
3663   CARLOS ANTONIO LAPIQUE MARTINEZ        PTN    22/10/1955  MASCULINO

[3664 rows x 4 columns]

In [4]:
dados = df.loc[df['DS_GENERO'] == 'FEMININO']

In [11]:
dados['NM_CANDIDATO']

1                  AUREA RODRIGUES MADEIRO
11                      MARIA JOSÉ OCAMPOS
15         ADRIANA SILVA RENAUT CAVALHEIRO
18      FRANCISCA PEREIRA DA ROCHA  SEIXAS
21                LUISA DA SILVA FERNANDES
                       ...
3653               NEUSA DOS ANJOS RUOTOLO
3654      ADRIANA SOUZA DOS SANTOS PEREIRA
3656                  GILVANA ALVES FARIAS
3657                  SILVANA INES MOREIRA
3661              MÔNICA DE OLIVEIRA COSTA
Name: NM_CANDIDATO, Length: 1124, dtype: object

In [12]:
dados.iloc[0:,[17,28,38,42]]

                            NM_CANDIDATO SG_PARTIDO DT_NASCIMENTO DS_GENERO
1                AUREA RODRIGUES MADEIRO       PMDB    18/02/1964  FEMININO
11                    MARIA JOSÉ OCAMPOS        PRB    29/06/1955  FEMININO
15       ADRIANA SILVA RENAUT CAVALHEIRO        PTC    04/05/1965  FEMININO
18    FRANCISCA PEREIRA DA ROCHA  SEIXAS    PC do B    17/04/1961  FEMININO
21              LUISA DA SILVA FERNANDES         PV    04/02/1985  FEMININO
...                                  ...        ...           ...       ...
3653             NEUSA DOS ANJOS RUOTOLO        PMN    20/08/1951  FEMININO
3654    ADRIANA SOUZA DOS SANTOS PEREIRA        PRP    17/11/1979  FEMININO
3656                GILVANA ALVES FARIAS        PRP    09/05/1972  FEMININO
3657                SILVANA INES MOREIRA        PRP    08/12/1964  FEMININO
3661            MÔNICA DE OLIVEIRA COSTA        PHS    28/03/1986  FEMININO

[1124 rows x 4 columns]