In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
df = pd.read_csv('/home/nayara/trabalhoPy/trabalhoPy_env/consulta_cand_2018_SP.csv',header=0,encoding='ISO-8859-1', delimiter=';')

In [3]:
df.iloc[0:,[17,28,38,42]]

                           NM_CANDIDATO SG_PARTIDO DT_NASCIMENTO  DS_GENERO
0           HENRIQUE CARVALHO DE CAMPOS       PODE    04/11/1957  MASCULINO
1                MICHEL RAMIRO CARNEIRO    PC do B    25/04/1987  MASCULINO
2     RAIMUNDO BERNARDINO DO NASCIMENTO         PT    31/05/1945  MASCULINO
3           MAURICIO DOMINGUES DA SILVA        PRB    09/08/1962  MASCULINO
4               ORLANDO MAURÍCIO JÚNIOR         PT    31/07/1975  MASCULINO
...                                 ...        ...           ...        ...
3947       LUIZ JACINTO NEPOMUCENO NETO        PHS    15/08/1971  MASCULINO
3948               MARCELA DIAS MOREIRA       PSOL    13/12/1980   FEMININO
3949                  JOSÉ LUIZ GLADCHI       PRTB    27/05/1953  MASCULINO
3950           EDUARDO RODRIGUES XAVIER        MDB    08/01/1971  MASCULINO
3951            HENRIQUE STEIN SCIASCIO        PRB    07/06/1985  MASCULINO

[3952 rows x 4 columns]

In [4]:
dados = df.loc[df['DS_GENERO'] == 'FEMININO']

In [5]:
dados['NM_CANDIDATO']

5               ROSANILDA ANTONIA DA SILVA
6       JAQUELINE LILIAN BARCELOS COUTINHO
9                DIANA SOUBIHE DE OLIVEIRA
10          LUCIANA FONTES LAVIERI ALBERTO
11          GISELLE  RISSAS POIATO BEZERRA
                       ...
3940                  TALITA EYMAEL LATÃES
3942        RITA DE CÁSSIA SANTANA ALBANEZ
3944                 ISABEL KAUSZ DOS REIS
3946         ROSA GOMES DA FONSECA RIBEIRO
3948                  MARCELA DIAS MOREIRA
Name: NM_CANDIDATO, Length: 1256, dtype: object

In [6]:
dados.iloc[0:,[17,28,38,42]]

                            NM_CANDIDATO SG_PARTIDO DT_NASCIMENTO DS_GENERO
5             ROSANILDA ANTONIA DA SILVA         PV    17/06/1962  FEMININO
6     JAQUELINE LILIAN BARCELOS COUTINHO        PTB    03/09/1966  FEMININO
9              DIANA SOUBIHE DE OLIVEIRA       PSOL    14/11/1985  FEMININO
10        LUCIANA FONTES LAVIERI ALBERTO       NOVO    21/10/1970  FEMININO
11        GISELLE  RISSAS POIATO BEZERRA        PTC    07/07/1984  FEMININO
...                                  ...        ...           ...       ...
3940                TALITA EYMAEL LATÃES         DC    27/08/1986  FEMININO
3942      RITA DE CÁSSIA SANTANA ALBANEZ        PRB    27/03/1972  FEMININO
3944               ISABEL KAUSZ DOS REIS        MDB    14/04/1970  FEMININO
3946       ROSA GOMES DA FONSECA RIBEIRO       PRTB    21/01/1959  FEMININO
3948                MARCELA DIAS MOREIRA       PSOL    13/12/1980  FEMININO

[1256 rows x 4 columns]